"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import time

N = int(4e6)


def fibonacci(n):
    """
        Generator of fibonacci sequence
    """
    a, b = 1, 2
    yield a
    yield b
    while b < n:
        a, b = b, a+b
        yield b


start_time = time.time()
result = sum((i for i in fibonacci(N) if i % 2 == 0))
final_time = time.time()
print("Result {} found in {:.6f}s".format(result, final_time-start_time))
